export const GET_ERRORS = "GET_ERRORS";

export const CREATE_CUST_PROFILE = "CREATE_CUST_PROFILE";
export const GET_CUST_PROFILE = "GET_CUST_PROFILE";
export const UPDATE_CUST_PROFILE = "UPDATE_CUST_PROFILE";
export const DELETE_CUST_PROFILE = "DELETE_CUST_PROFILE";

export const CREATE_DRIVER_PROFILE = "CREATE_DRIVER_PROFILE";
export const GET_DRIVER_PROFILE = "GET_DRIVER_PROFILE";
export const UPDATE_DRIVER_PROFILE = "UPDATE_DRIVER_PROFILE";
export const DELETE_DRIVER_PROFILE = "DELETE_DRIVER_PROFILE";
export const GET_DRIVERS = "GET_DRIVERS";

export const INSERT_CAB_DETAILS = "INSERT_CAB_DETAILS";
export const GET_CAB_DETAILS = "GET_CAB_DETAILS";
export const UPDATE_CAB_DETAILS = "UPDATE_CAB_DETAILS";
export const DELETE_CAB_DETAILS = "DELETE_CAB_DETAILS";

export const INSERT_TRIP = "INSERT_TRIP";
export const GET_CUST_TRIPS = "GET_TRIPS";
export const UPDATE_TRIP = "UPDATE_TRIP";
export const DELETE_TRIP = "DELETE_TRIP";