export const GET_TRIPS= "GET_TRIPS";
export const GET_TRIPCABWISE = "GET_TRIPCABWISE";
export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_DRIVER = "GET_DRIVER";
export const GET_CAB = "GET_CAB";
export const DELETE_DRIVER = "DELETE_DRIVER";
export const DELETE_CAB = "DELETE_CAB";
export const DRIVER_DETAIL_AUTO = "DRIVER_DETAIL_AUTO";

export const DRIVER_DETAIL_MINI = "DRIVER_DETAIL_MINI";

export const DRIVER_DETAIL_PRIME ="DRIVER_DETAIL_PRIME";

export const GET_TRIPS_TABLE ="GET_TRIPS_TABLE";